spring:
  mvc:
    view:
      suffix: .html

  jpa:
    show-sql: true
    database: mysql

    hibernate:
      ddl-auto: create
    # Hibernate ddl auto (create, create-drop, validate, update)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/foo
    username: root
    password: mariadb

  servlet:
      multipart:
      max-request-size: 20MB
      max-file-size: 20MB
